/*
  NARRAÇÃO
  1. LANÇAMENTO
    1. LANÇAMENTO EM PROFUNDIDADE POR TRÁS DO ZAGUEIRO
      1. FORTE DEMAIS, FICOU COM O GOLEIRO 0.6
      2. CORTA A DEFESA 0.3
      3. DOMINOU E FICOU NA CARA DO GOL 0.1
        -> CHUTE DE CARA PRO GOL
    2. LANÇAMENTO EM PROFUNDIDADE NA PONTA
      1. FORTE DEMAIS E A BOLA SAI 0.2
      2. CORTA A DEFESA 0.2
      3. RECEBEU A BOLA O PONTA 0.6
        -> JOGADA LATERAL 2.1
        
  2. JOGADA LATERAL
    O PASSE VEM PARA A LATERAL
    2.1 PROCURA O ESPAÇO PARA O CRUZAMENTO
      1. ACHA UM ESPEÇO MELHOR E VAI EM DIREÇÃO A GRANDE AREA 0.1
        -> CRUZAMENTO PASSE CURTO
      2. CRUZAMENTO CRUZAMENTO 0.5
      3. A DEFESA CORTA E RETOMA A POSSE DE BOLA 0.4

  3. JOGADAS CENTRAIS
    MENTEM A POSSE E BUSCA ESPACO
    TENTA O PASSE PARA FRENTE
    1. PASSE EM PROFUNDIDADE ENTRE OS ZAGUEIROS 0.1
      FICOU NA CARA DO GOLEIRO
      -> CHANCE NA CARA DO GOL
    2. ACHA UM PASSE INTERESSANTE NO MEIO DA DEFESA 0.3
      RECEBE A BOLA E FAZ O PASSE PARA O CHUTE DO COMPANHEIRO
        -> CHUTE
    3. VOLTA A BOLA 0.4
      TENTA O CHUTE DE LONGE
      -> CHUTE LONGE
    3. ERROU O PASSE 0.2
  4. FALTAS
    // 1. PENALTI
    2. CHUTE DE FALTA LONGE
    2. CHUTE DE FALTA PERTO
  5. ESCANTEIO
    -> CRUZAMENTO. 
    
  CRUZAMENTO
    PASSE CURTO
      TENTA O PASSE VOLTANDO
      1. A DEFESA FICA COM A BOLA
      2. CONSEGUE O ESPAÇO PARA O CHUTE
        -> CHUTE
    CRUZAMENTO
      1. A DEFESA TIRA 0.5
      2. O GOLEIRO FICA COM ELA 0.2
      3. -> CABEÇADA 0.3

  CHANCES DE GOL
  1. CABEÇADA
    1.1 FORA 0.4
    1.2 DEFESA 0.2
    1.3 GOL 0.4
  2. CHUTE DE CARA
    5.1 GOL 0.6
    5.2 DEFESA 0.2
    5.4 FORA 0.2
  2. CHUTE
    2.1 GOL 0.3
    2.2 DEFESA 0.3
    2.3 FORA 0.1
    2.4 BLOUEADO 0.2
    2.5 REBOTE 0.1
  3. CHUTE DE LONGE
    3.1 GOL 0.1
    3.2 DEFESA 0.3
    3.3 BLOQUEADO 0.1
    3.1 FORA 0.5
  4. CHUTE DE FALTA
    1. PERTO
      4.1 GOL 0.2
      4.2 BATE NA BARREIRA 0.3
      4.3 FORA 0.3
      4.4 DEFESA 0.2
    2. LONGE
      4.1 GOLAÇO 0.05
      4.2 BATE NA BARREIRA 0.1
      4.3 FORA 0.25
      4.4 CRUZAMENTO 0.6  
  5. REBOTE
    5.1 GOL 0.7
    5.2 DEFESA 0.1
    5.3 BLOQUEADO 0.1
    5.4 FORA 0.1
  6. PENALTI
    5. GOL 0.7
    6. DEFESA 0.15
    7. FORA 0.1
    8. REBOTE 0.05
  */
